FROM mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD="Pass!@word"
EXPOSE 1433


# docker build -t db_prueba_tecnica .
# docker run  -d  --name dbpruebatecnica -p 1433:1433/tcp db_prueba_tecnica